Repository juspay/hyperswitch, pull requests merged in 2023-02, with the labels that each got.

#485 test(connector): add and update tests for stripe, cybersource and shift4 connectors
  connector-template/mod.rs
  connector-template/test.rs
  connector-template/transformers.rs
  crates/router/src/connector/authorizedotnet/transformers.rs
  crates/router/src/connector/checkout.rs
  crates/router/src/connector/cybersource.rs
  crates/router/src/connector/cybersource/transformers.rs
  crates/router/src/connector/shift4.rs
  crates/router/src/connector/shift4/transformers.rs
  crates/router/src/connector/stripe.rs
  crates/router/src/connector/utils.rs
  crates/router/src/connector/worldline.rs
  crates/router/tests/connectors/cybersource.rs
  crates/router/tests/connectors/fiserv.rs
  crates/router/tests/connectors/globalpay.rs
  crates/router/tests/connectors/payu.rs
  crates/router/tests/connectors/rapyd.rs
  crates/router/tests/connectors/shift4.rs
  crates/router/tests/connectors/stripe.rs
  crates/router/tests/connectors/utils.rs
  crates/router/tests/connectors/worldline.rs
  crates/router/tests/connectors/worldpay.rs
  scripts/add_connector.sh
Labels: A-connector-integration, S-waiting-on-review

#487 feat: Add update endpoint for config
  crates/router/src/core/configs.rs
  crates/router/src/db/configs.rs
  crates/router/src/routes/app.rs
  crates/router/src/routes/configs.rs
  crates/router/src/types/api/configs.rs
  crates/router/src/types/transformers.rs
  crates/router_env/src/logger/types.rs
Labels: A-core, C-feature

#482 perf(router): remove redundant DB call during merchant account update
  crates/router/src/core/admin.rs
  crates/router/src/db/merchant_account.rs
  crates/storage_models/src/merchant_account.rs
  crates/storage_models/src/query/generics.rs
  crates/storage_models/src/query/merchant_account.rs
Labels: S-ready-to-merge, A-performance

#480 feat(consumer): add `workflow_id` field in traces for consumer tasks
  crates/router/src/scheduler/consumer.rs
  crates/router/src/scheduler/workflows.rs
  crates/router/src/scheduler/workflows/payment_sync.rs
  crates/router_env/src/logger/formatter.rs
Labels: A-process-tracker, C-feature, S-ready-to-merge

#490 feat: renaming services in docker-compose and set execution order
  config/docker_compose.toml
  docker-compose.yml
Labels: A-infra, S-ready-to-merge

#481 feat(config): add fetch endpoint for config table
  crates/redis_interface/src/commands.rs
  crates/router/src/compatibility/stripe/errors.rs
  crates/router/src/core.rs
  crates/router/src/core/configs.rs
  crates/router/src/core/errors/api_error_response.rs
  crates/router/src/db/configs.rs
  crates/router/src/lib.rs
  crates/router/src/routes.rs
  crates/router/src/routes/app.rs
  crates/router/src/routes/configs.rs
  crates/router/src/types/api.rs
  crates/router/src/types/api/configs.rs
  crates/router/src/types/transformers.rs
  crates/router_env/src/logger/types.rs
  crates/storage_models/src/configs.rs
Labels: A-core, C-feature, S-waiting-on-review, S-ready-to-merge

#493 fix(refund): fix failing refund update with KV storage backend
  crates/storage_models/src/query/refund.rs
Labels: A-core, C-bug, S-ready-to-merge

#494 fix: don't panic in redis library on creating connection pool
  crates/drainer/src/connection.rs
  crates/redis_interface/src/commands.rs
  crates/redis_interface/src/errors.rs
  crates/redis_interface/src/lib.rs
  crates/router/src/connection.rs
Labels: A-framework, C-bug, S-waiting-on-review

#489 fix: fix KV implementations for payments and refunds
  crates/router/src/db/payment_attempt.rs
  crates/router/src/db/refund.rs
  crates/storage_models/src/reverse_lookup.rs
Labels: A-core, C-bug, S-waiting-on-review, S-ready-to-merge, A-performance

#495 feat: Add logging functionality in drainer
  crates/drainer/src/env.rs
  crates/drainer/src/errors.rs
  crates/drainer/src/lib.rs
  crates/drainer/src/main.rs
  crates/drainer/src/services.rs
  crates/drainer/src/utils.rs
Labels: A-framework, A-drainer, S-ready-to-merge, A-performance

#486 docs: add Windows setup instructions and update Postman docs
  .devcontainer/devcontainer.json
  docs/try_local_system.md
  postman/README.md
  postman/collection.postman.json
Labels: C-doc

#483 feat(cache): add generic cache functions to populate and invalidate cache
  crates/router/src/db.rs
  crates/router/src/db/cache.rs
Labels: A-framework, A-core, C-feature, S-ready-to-merge

#500 update readme
  README.md
Labels: C-doc

#497 feat: add metrics to drainer
  Cargo.lock
  crates/common_utils/src/lib.rs
  crates/drainer/Cargo.toml
  crates/drainer/src/lib.rs
  crates/drainer/src/metrics.rs
  crates/drainer/src/utils.rs
  crates/router/src/scheduler/metrics.rs
Labels: A-framework, A-drainer

#435 Rapyd webhook integration
  crates/router/src/connector/adyen.rs
  crates/router/src/connector/rapyd.rs
  crates/router/src/connector/rapyd/transformers.rs
  crates/router/src/connector/stripe.rs
  crates/router/src/connector/utils.rs
  crates/router/src/types/api/webhooks.rs
Labels: A-connector-integration

#499 refactor: AppState trait for utility functions
  crates/router/src/compatibility/stripe/customers.rs
  crates/router/src/compatibility/stripe/payment_intents.rs
  crates/router/src/compatibility/stripe/refunds.rs
  crates/router/src/compatibility/stripe/setup_intents.rs
  crates/router/src/compatibility/wrap.rs
  crates/router/src/routes/admin.rs
  crates/router/src/routes/app.rs
  crates/router/src/routes/configs.rs
  crates/router/src/routes/customers.rs
  crates/router/src/routes/ephemeral_key.rs
  crates/router/src/routes/mandates.rs
  crates/router/src/routes/payment_methods.rs
  crates/router/src/routes/payments.rs
  crates/router/src/routes/refunds.rs
  crates/router/src/routes/webhooks.rs
  crates/router/src/services/api.rs
  crates/router/src/services/authentication.rs
Labels: A-core, C-refactor, S-ready-to-merge

#496 refactor: use generic function to push to drainer
  crates/router/src/db/payment_attempt.rs
  crates/router/src/db/payment_intent.rs
  crates/router/src/db/refund.rs
  crates/router/src/services.rs
Labels: A-core, C-refactor, S-ready-to-merge

#502 feat(generics): allow specifying optional offset and order clauses for `generic_filter()`
  crates/storage_models/src/query/generics.rs
  crates/storage_models/src/query/mandate.rs
  crates/storage_models/src/query/merchant_connector_account.rs
  crates/storage_models/src/query/payment_attempt.rs
  crates/storage_models/src/query/payment_method.rs
  crates/storage_models/src/query/process_tracker.rs
  crates/storage_models/src/query/refund.rs
Labels: A-framework, C-feature, S-ready-to-merge

#503 fix(storage_models): fix inconsistent field order for merchant account types
  crates/storage_models/src/merchant_account.rs
  crates/storage_models/src/schema.rs
Labels: A-framework, C-bug, S-ready-to-merge

#498 feat: Add graceful shutdown in drainer
  Cargo.lock
  config/config.example.toml
  crates/common_utils/Cargo.toml
  crates/common_utils/src/lib.rs
  crates/common_utils/src/signals.rs
  crates/drainer/src/errors.rs
  crates/drainer/src/lib.rs
  crates/drainer/src/main.rs
  crates/drainer/src/metrics.rs
  crates/drainer/src/settings.rs
  crates/router/src/scheduler/consumer.rs
Labels: A-process-tracker, M-configuration-changes, A-drainer

#505 fix: decide refund type by the request and not defaults
  crates/router/src/core/refunds.rs
Labels: A-core, C-bug, S-ready-to-merge

#506 chore: use generic cache functions for config table
  crates/router/src/db/cache.rs
  crates/router/src/db/configs.rs
Labels: A-core, C-refactor, S-ready-to-merge

#507 fix(router): fix payment token null in payment update api response
  crates/router/src/core/payments/operations/payment_update.rs
  crates/storage_models/src/payment_attempt.rs
Labels: A-core, C-bug, S-ready-to-merge

#508 feat(db): add fetch and update cache for admin table
  crates/router/Cargo.toml
  crates/router/src/db/cache.rs
  crates/router/src/db/merchant_account.rs
  crates/storage_models/src/merchant_account.rs
Labels: A-core, C-feature, S-ready-to-merge

#509 feat: add timeout for `set` command on hashes and add function to allow retry in database
  config/config.example.toml
  crates/redis_interface/src/commands.rs
  crates/redis_interface/src/lib.rs
  crates/redis_interface/src/types.rs
  crates/router/src/db/payment_attempt.rs
  crates/router/src/db/payment_intent.rs
  crates/router/src/db/refund.rs
  crates/router/src/routes/metrics.rs
  crates/router/src/utils/db_utils.rs
Labels: A-core, M-configuration-changes, S-ready-to-merge

#512 fix: fix bugs found when testing drainer
  crates/router/src/db/payment_attempt.rs
  crates/storage_models/src/payment_attempt.rs
  crates/storage_models/src/refund.rs
Labels: A-core, C-bug, S-ready-to-merge

#514 refactor: use unique id for merchant_conenctor_id instead of int
  crates/api_models/src/admin.rs
  crates/router/src/core/admin.rs
  crates/router/src/db/merchant_connector_account.rs
  crates/router/src/routes/admin.rs
  crates/storage_models/src/merchant_connector_account.rs
  crates/storage_models/src/query/merchant_connector_account.rs
  crates/storage_models/src/schema.rs
  migrations/2023-02-07-070512_change_merchant_connector_id_data_type/down.sql
  migrations/2023-02-07-070512_change_merchant_connector_id_data_type/up.sql
Labels: A-core, M-database-changes, S-ready-to-merge

#517 feat: add tick interval to drainer
  config/config.example.toml
  crates/drainer/src/lib.rs
  crates/drainer/src/main.rs
  crates/drainer/src/settings.rs
  crates/drainer/src/utils.rs
  crates/router/src/configs/defaults.rs
  crates/router/src/configs/settings.rs
Labels: A-drainer, S-ready-to-merge

#518 feat: add a kv switch route for merchants
  crates/api_models/src/admin.rs
  crates/router/src/core/admin.rs
  crates/router/src/routes/admin.rs
  crates/router/src/routes/app.rs
  crates/router/src/types/api/admin.rs
  crates/storage_models/src/merchant_account.rs
Labels: A-core

#520 docs(try_local_system): add next steps after installing dependencies on Windows
  docs/try_local_system.md
Labels: C-doc

#521 fix: fix the loader orientation on mobile
  crates/router/src/services/api.rs
Labels: A-core, C-bug, S-ready-to-merge

#516 feat(connector): add afterpay,klarna,affirm support in adyen connector
  crates/router/src/connector/adyen.rs
  crates/router/src/connector/adyen/transformers.rs
  crates/router/src/connector/utils.rs
  crates/router/tests/connectors/adyen.rs
  crates/router/tests/connectors/connector_auth.rs
  crates/router/tests/connectors/main.rs
  crates/router/tests/connectors/sample_auth.toml
Labels: A-connector-integration, C-feature, S-ready-to-merge

#530 ci: run CI checks on merge queue events
  .github/workflows/CI.yml
Labels: A-CI-CD, C-feature

#515 feat: Impelement redis cache for MCA fetch and update
  crates/router/src/db/merchant_connector_account.rs
  crates/storage_models/src/merchant_connector_account.rs
Labels: A-core, C-feature

#522 fix(core): use guard for access token result
  crates/router/src/core/payments.rs
  crates/router/src/core/payments/access_token.rs
  crates/router/src/core/refunds.rs
Labels: C-bug, S-waiting-on-review

#511 feat(router): implement API endpoints for managing API keys
  Cargo.lock
  crates/api_models/src/api_keys.rs
  crates/api_models/src/lib.rs
  crates/common_utils/Cargo.toml
  crates/common_utils/src/crypto.rs
  crates/router/Cargo.toml
  crates/router/src/compatibility/stripe/errors.rs
  crates/router/src/consts.rs
  crates/router/src/core.rs
  crates/router/src/core/admin.rs
  crates/router/src/core/api_keys.rs
  crates/router/src/core/errors.rs
  crates/router/src/core/errors/api_error_response.rs
  crates/router/src/db.rs
  crates/router/src/db/api_keys.rs
  crates/router/src/lib.rs
  crates/router/src/openapi.rs
  crates/router/src/routes.rs
  crates/router/src/routes/api_keys.rs
  crates/router/src/routes/app.rs
  crates/router/src/types/api.rs
  crates/router/src/types/api/api_keys.rs
  crates/router/src/types/storage.rs
  crates/router/src/types/storage/api_keys.rs
  crates/router/src/types/transformers.rs
  crates/router_env/src/env.rs
  crates/router_env/src/logger/types.rs
  crates/storage_models/src/api_keys.rs
  crates/storage_models/src/lib.rs
  crates/storage_models/src/query.rs
  crates/storage_models/src/query/api_keys.rs
  crates/storage_models/src/schema.rs
  migrations/2023-02-01-135102_create_api_keys_table/down.sql
  migrations/2023-02-01-135102_create_api_keys_table/up.sql
  openapi/generated.json
Labels: A-core, C-feature, M-database-changes

#524 Add a base struct for api error responses
  Cargo.lock
  crates/api_models/Cargo.toml
  crates/api_models/src/errors/actix.rs
  crates/api_models/src/errors/mod.rs
  crates/api_models/src/errors/serde.rs
  crates/api_models/src/errors/types.rs
  crates/api_models/src/lib.rs
  crates/common_utils/src/errors.rs
Labels: A-framework, C-refactor

#534 build(docker-compose): increase docker health check interval for hyperswitch-server
  docker-compose.yml
Labels: C-refactor

#536 fix(router): feature gate openssl deps for basilisk feature
  crates/router/Cargo.toml
  crates/router/src/core/payment_methods/vault.rs
  crates/router/src/services.rs
  crates/router/src/services/encryption.rs
Labels: A-dependencies

#584 docs(add_connector): fix typo
  add_connector.md
Labels: C-doc, S-waiting-on-review

#587 refactor(middleware): change visibility to `pub`
  crates/router/src/lib.rs
  crates/router/src/middleware.rs
Labels: A-framework, S-waiting-on-review, C-refactor

#526 refactor: send full payment object for payment sync
  crates/router/src/core/payments/operations/payment_response.rs
Labels: A-core, C-refactor

#588 refactor(router): appstate as trait in authentication
  crates/router/src/services/authentication.rs
  crates/router/src/utils.rs
Labels: C-refactor

#531 fix: throw 500 error when redis goes down
  crates/redis_interface/src/lib.rs
  crates/router/src/core/errors.rs
  crates/router/src/db/cache.rs
  crates/router/src/db/ephemeral_key.rs
  crates/router/src/db/merchant_connector_account.rs
  crates/router/src/db/payment_attempt.rs
  crates/router/src/db/payment_intent.rs
  crates/router/src/db/queue.rs
  crates/router/src/db/refund.rs
  crates/router/src/scheduler/producer.rs
  crates/router/src/scheduler/utils.rs
  crates/router/src/services.rs
Labels: A-core

#527 refactor: Throw 500 error on database connection error instead of panic
  config/Development.toml
  config/config.example.toml
  crates/router/src/configs/defaults.rs
  crates/router/src/configs/settings.rs
  crates/router/src/connection.rs
  crates/router/src/core/errors.rs
  crates/router/src/db/address.rs
  crates/router/src/db/api_keys.rs
  crates/router/src/db/configs.rs
  crates/router/src/db/connector_response.rs
  crates/router/src/db/customers.rs
  crates/router/src/db/events.rs
  crates/router/src/db/locker_mock_up.rs
  crates/router/src/db/mandate.rs
  crates/router/src/db/merchant_account.rs
  crates/router/src/db/merchant_connector_account.rs
  crates/router/src/db/payment_attempt.rs
  crates/router/src/db/payment_intent.rs
  crates/router/src/db/payment_method.rs
  crates/router/src/db/process_tracker.rs
  crates/router/src/db/refund.rs
  crates/router/src/db/reverse_lookup.rs
  loadtest/config/Development.toml
Labels: A-core, M-configuration-changes

#592 feat: add `track_caller` to functions that perform `change_context`
  crates/router/src/core/errors/utils.rs
Labels: A-core, C-feature

#525 fix: don't call connector if connector transaction id doesn't exist
  crates/router/src/core/payments/helpers.rs
  crates/router/src/core/payments/operations/payment_status.rs
Labels: C-bug

#532 feat(api_models): add error structs
  crates/api_models/src/errors/actix.rs
  crates/api_models/src/errors/mod.rs
  crates/api_models/src/errors/serde.rs
  crates/api_models/src/errors/types.rs
  crates/common_utils/src/errors.rs
  crates/router/src/compatibility/stripe/errors.rs
  crates/router/src/compatibility/wrap.rs
  crates/router/src/core/errors/api_error_response.rs
  crates/router/src/core/errors/error_handlers.rs
  crates/router/src/core/errors/utils.rs
  crates/router/src/services/api.rs
Labels: C-refactor

#596 fix(checkout): Error Response when wrong api key is passed
  crates/router/src/connector/checkout.rs
Labels: A-connector-integration, C-bug

#600 refactor(router): api-key routes refactoring
  crates/router/src/routes/api_keys.rs
  crates/router/src/routes/app.rs
  crates/router/src/services/authentication.rs
Labels: A-core, C-refactor

#601 fix: allow errors with status code 200 to pass
  crates/router/src/core/payments/operations/payment_response.rs
Labels: A-core, C-bug

#609 bugfix(router): api keys path params
  crates/router/src/routes/api_keys.rs
Labels: A-core, C-bug

#612 chore(release): port release bug fixes to main branch
  CHANGELOG.md
  crates/router/src/core/payments.rs
Labels: A-core

#491 refactor: add payment_issuer and payment_experience in pa
  Cargo.lock
  crates/api_models/src/admin.rs
  crates/api_models/src/enums.rs
  crates/api_models/src/payment_methods.rs
  crates/api_models/src/payments.rs
  crates/common_utils/src/custom_serde.rs
  crates/router/src/connector/aci/transformers.rs
  crates/router/src/connector/adyen/transformers.rs
  crates/router/src/connector/authorizedotnet/transformers.rs
  crates/router/src/connector/braintree/transformers.rs
  crates/router/src/connector/checkout/transformers.rs
  crates/router/src/connector/cybersource/transformers.rs
  crates/router/src/connector/fiserv/transformers.rs
  crates/router/src/connector/globalpay/transformers.rs
  crates/router/src/connector/klarna.rs
  crates/router/src/connector/klarna/transformers.rs
  crates/router/src/connector/payu/transformers.rs
  crates/router/src/connector/rapyd/transformers.rs
  crates/router/src/connector/shift4/transformers.rs
  crates/router/src/connector/stripe/transformers.rs
  crates/router/src/connector/worldline/transformers.rs
  crates/router/src/connector/worldpay.rs
  crates/router/src/connector/worldpay/transformers.rs
  crates/router/src/core/errors.rs
  crates/router/src/core/errors/utils.rs
  crates/router/src/core/payment_methods/cards.rs
  crates/router/src/core/payment_methods/transformers.rs
  crates/router/src/core/payments/operations/payment_create.rs
  crates/router/src/core/payments/operations/payment_response.rs
  crates/router/src/core/payments/transformers.rs
  crates/router/src/db/payment_attempt.rs
  crates/router/src/openapi.rs
  crates/router/src/types.rs
  crates/router/src/types/transformers.rs
  crates/router/tests/connectors/aci.rs
  crates/router/tests/connectors/adyen.rs
  crates/router/tests/connectors/authorizedotnet.rs
  crates/router/tests/connectors/checkout.rs
  crates/router/tests/connectors/utils.rs
  crates/router/tests/connectors/worldline.rs
  crates/router/tests/payments.rs
  crates/router/tests/payments2.rs
  crates/router_derive/Cargo.toml
  crates/router_derive/src/lib.rs
  crates/router_derive/src/macros.rs
  crates/router_derive/src/macros/diesel.rs
  crates/storage_models/src/enums.rs
  crates/storage_models/src/payment_attempt.rs
  crates/storage_models/src/schema.rs
  migrations/2023-02-02-055700_add_payment_issuer_and_experience_in_payment_attempt/down.sql
  migrations/2023-02-02-055700_add_payment_issuer_and_experience_in_payment_attempt/up.sql
  migrations/2023-02-02-062215_remove_redirect_and_payment_flow_from_payment_attempt/down.sql
  migrations/2023-02-02-062215_remove_redirect_and_payment_flow_from_payment_attempt/up.sql
  openapi/generated.json
Labels: A-connector-integration, A-core, M-database-changes

#604 refactor(core): make attempt id as mandatory in router_data
  crates/router/src/connector/globalpay/transformers.rs
  crates/router/src/connector/utils.rs
  crates/router/src/connector/worldpay/transformers.rs
  crates/router/src/core/payments/transformers.rs
  crates/router/src/core/utils.rs
  crates/router/src/types.rs
  crates/router/tests/connectors/aci.rs
  crates/router/tests/connectors/authorizedotnet.rs
  crates/router/tests/connectors/checkout.rs
  crates/router/tests/connectors/utils.rs
Labels: A-core, C-refactor

#605 refactor: use simple uuid instead of hyphens
  crates/router/src/core/payments/operations/payment_create.rs
  crates/router/src/core/payments/operations/payment_method_validate.rs
Labels: A-core, C-feature

#610 fix(router): allow setup future usage to be updated in payment update and confirm requests
  crates/router/src/core/payments/operations/payment_confirm.rs
  crates/router/src/core/payments/operations/payment_update.rs
  crates/storage_models/src/payment_intent.rs
Labels: A-core, C-bug

#611 Release v0.2.1
  .github/workflows/CI.yml
  CHANGELOG.md
  README.md
  crates/api_models/src/payments.rs
  crates/router/src/core/payments.rs
  crates/router/src/core/payments/access_token.rs
  crates/router/src/core/payments/helpers.rs
  crates/router/src/core/payments/operations/payment_update.rs
  crates/router/src/core/refunds.rs
  crates/router/src/lib.rs
  crates/router/src/middleware.rs
  crates/router/src/openapi.rs
  crates/router/src/services/api.rs
  crates/router/src/utils/ext_traits.rs
  crates/storage_models/src/merchant_account.rs
  crates/storage_models/src/query/generics.rs
  crates/storage_models/src/refund.rs
  crates/storage_models/src/schema.rs
  docs/imgs/download-button.png
  docs/try_sandbox.md
  openapi/generated.json
  openapi/open_api_spec.yaml
Labels: A-core

#599 feat: initial `nix` setup using `cargo2nix`
  .gitignore
  .typos.toml
  Cargo.nix
  docs/try_local_system.md
  flake.lock
  flake.nix
Labels: C-feature

#613 refactor(redirection): `From` impl for redirection data for ease of use
  crates/router/src/connector/adyen/transformers.rs
  crates/router/src/connector/checkout/transformers.rs
  crates/router/src/connector/rapyd/transformers.rs
  crates/router/src/connector/stripe/transformers.rs
  crates/router/src/services/api.rs
Labels: C-refactor

#627 fix: add zero-padded formatting for error code
  crates/api_models/src/errors/types.rs
Labels: A-core, S-waiting-on-review

#519 feat: applepay payment request object
  crates/api_models/src/payments.rs
  crates/router/src/connector/applepay.rs
  crates/router/src/connector/applepay/transformers.rs
  crates/router/src/connector/braintree/transformers.rs
  crates/router/src/connector/klarna/transformers.rs
  crates/router/src/core/payments/flows/session_flow.rs
  crates/router/src/openapi.rs
  openapi/generated.json
Labels: A-connector-integration, C-feature, S-waiting-on-review

#614 feat: Add support for a redis pubsub interface
  Cargo.lock
  crates/redis_interface/Cargo.toml
  crates/redis_interface/src/errors.rs
  crates/redis_interface/src/lib.rs
  crates/router/src/consts.rs
  crates/router/src/macros.rs
  crates/router/src/services.rs
Labels: A-framework, S-waiting-on-review

#636 feat: applepay feature release
  crates/api_models/src/payments.rs
  crates/router/src/connector/applepay.rs
  crates/router/src/connector/applepay/transformers.rs
  crates/router/src/connector/braintree/transformers.rs
  crates/router/src/connector/klarna/transformers.rs
  crates/router/src/core/payments/flows/session_flow.rs
  crates/router/src/openapi.rs
  openapi/generated.json
Labels: A-core, C-feature

#637 enhance(router/webhooks): expose additional incoming request details to webhooks flow
  connector-template/mod.rs
  crates/api_models/src/webhooks.rs
  crates/router/src/connector/aci.rs
  crates/router/src/connector/adyen.rs
  crates/router/src/connector/applepay.rs
  crates/router/src/connector/authorizedotnet.rs
  crates/router/src/connector/braintree.rs
  crates/router/src/connector/checkout.rs
  crates/router/src/connector/cybersource.rs
  crates/router/src/connector/fiserv.rs
  crates/router/src/connector/globalpay.rs
  crates/router/src/connector/klarna.rs
  crates/router/src/connector/payu.rs
  crates/router/src/connector/rapyd.rs
  crates/router/src/connector/shift4.rs
  crates/router/src/connector/stripe.rs
  crates/router/src/connector/worldline.rs
  crates/router/src/connector/worldpay.rs
  crates/router/src/core/webhooks.rs
  crates/router/src/routes/app.rs
  crates/router/src/types/api/webhooks.rs
Labels: A-core, C-feature

#634 docs(api_models): fix typo
  crates/api_models/src/payments.rs
  openapi/generated.json
Labels: C-doc

#619 fix: add currency in verify request data
  crates/router/src/core/payments/transformers.rs
  crates/router/src/types.rs
Labels: A-connector-integration, A-core

#644 feat(router): include eligible connectors list in list payment methods
  crates/api_models/src/payment_methods.rs
  crates/router/src/core/payment_methods/cards.rs
Labels: A-core, C-feature, S-ready-for-merge

#523 refactor: Pass country and currency as json format in MCA
  crates/api_models/src/admin.rs
  crates/api_models/src/payment_methods.rs
  crates/router/src/core/admin.rs
  crates/router/src/core/payment_methods/cards.rs
  crates/router/src/routes/payment_methods.rs
Labels: A-payment-methods, C-refactor

#618 refactor(compatibility): add additional fields to stripe payment and refund response types
  crates/api_models/src/payments.rs
  crates/router/src/compatibility/stripe/payment_intents/types.rs
  crates/router/src/compatibility/stripe/refunds/types.rs
  crates/router/src/compatibility/wrap.rs
  crates/router/src/core/payments.rs
  crates/router/src/core/payments/transformers.rs
Labels: A-connector-compatibility, C-refactor

#643 refactor(router): update payments api contract to accept a list of connectors
  crates/api_models/src/payments.rs
  crates/router/src/compatibility/stripe/payment_intents/types.rs
  crates/router/src/core/payments/operations/payment_confirm.rs
  crates/router/src/core/payments/operations/payment_create.rs
Labels: A-core, C-refactor, S-ready-for-merge

#638 fix(router): allow setup future usage to be updated in payment update and confirm requests (#610)
  crates/router/src/core/payments/operations/payment_confirm.rs
  crates/router/src/core/payments/operations/payment_update.rs
  crates/storage_models/src/payment_intent.rs
Labels: A-core, C-bug

#642 refactor(connector): remove `peek()` on PII info
  crates/masking/src/secret.rs
  crates/router/src/connector/aci/transformers.rs
  crates/router/src/connector/authorizedotnet/transformers.rs
  crates/router/src/connector/braintree/transformers.rs
  crates/router/src/connector/cybersource/transformers.rs
  crates/router/src/connector/globalpay.rs
  crates/router/src/connector/globalpay/requests.rs
  crates/router/src/connector/globalpay/transformers.rs
  crates/router/src/connector/shift4/transformers.rs
  crates/router/src/connector/utils.rs
  crates/router/src/connector/worldpay/requests.rs
  crates/router/src/connector/worldpay/transformers.rs
  crates/router/src/core/errors/api_error_response.rs
  crates/router/src/core/payments/operations/payment_response.rs
  crates/router/tests/connectors/globalpay.rs
Labels: A-connector-integration, C-refactor

#641 enhance(router): release candidate pr for webhooks enhancement (#637)
  connector-template/mod.rs
  crates/api_models/src/webhooks.rs
  crates/router/src/connector/aci.rs
  crates/router/src/connector/adyen.rs
  crates/router/src/connector/applepay.rs
  crates/router/src/connector/authorizedotnet.rs
  crates/router/src/connector/braintree.rs
  crates/router/src/connector/checkout.rs
  crates/router/src/connector/cybersource.rs
  crates/router/src/connector/fiserv.rs
  crates/router/src/connector/globalpay.rs
  crates/router/src/connector/klarna.rs
  crates/router/src/connector/nuvei.rs
  crates/router/src/connector/payu.rs
  crates/router/src/connector/rapyd.rs
  crates/router/src/connector/shift4.rs
  crates/router/src/connector/stripe.rs
  crates/router/src/connector/worldline.rs
  crates/router/src/connector/worldpay.rs
  crates/router/src/core/webhooks.rs
  crates/router/src/routes/app.rs
  crates/router/src/types/api/webhooks.rs
Labels: A-core, C-feature

#621 refactor: add better log to parse struct
  crates/common_utils/src/ext_traits.rs
Labels: C-refactor

#624 chore(connectors): log connector request and response at debug level
  crates/router/src/connector/aci.rs
  crates/router/src/connector/braintree.rs
  crates/router/src/connector/checkout.rs
  crates/router/src/connector/cybersource.rs
  crates/router/src/connector/globalpay.rs
  crates/router/src/connector/klarna.rs
  crates/router/src/connector/payu.rs
  crates/router/src/connector/shift4.rs
  crates/router/src/connector/stripe.rs
  crates/router/src/connector/worldpay.rs
  crates/router/src/services/api.rs
Labels: A-connector-integration

#650 feat(connector): add authorize, capture, void, refund, psync, rsync support for Dlocal connector
  config/Development.toml
  config/config.example.toml
  config/docker_compose.toml
  crates/api_models/src/enums.rs
  crates/common_utils/src/lib.rs
  crates/router/src/configs/settings.rs
  crates/router/src/connector.rs
  crates/router/src/connector/dlocal.rs
  crates/router/src/connector/dlocal/transformers.rs
  crates/router/src/connector/utils.rs
  crates/router/src/lib.rs
  crates/router/src/types/api.rs
  crates/router/tests/connectors/connector_auth.rs
  crates/router/tests/connectors/dlocal.rs
  crates/router/tests/connectors/main.rs
  crates/router/tests/connectors/sample_auth.toml
  loadtest/config/Development.toml
Labels: A-connector-integration, C-feature

#649 feat(connector): [Bluesnap] add authorize, capture, void, refund, psync, rsync and Webhooks support
  Cargo.lock
  config/Development.toml
  config/config.example.toml
  config/docker_compose.toml
  crates/api_models/src/enums.rs
  crates/common_utils/Cargo.toml
  crates/common_utils/src/crypto.rs
  crates/router/src/configs/settings.rs
  crates/router/src/connector.rs
  crates/router/src/connector/bluesnap.rs
  crates/router/src/connector/bluesnap/transformers.rs
  crates/router/src/types.rs
  crates/router/src/types/api.rs
  crates/router/tests/connectors/bluesnap.rs
  crates/router/tests/connectors/connector_auth.rs
  crates/router/tests/connectors/main.rs
  loadtest/config/Development.toml
Labels: A-connector-integration, S-waiting-on-review

#646 feat(connector): [Airwallex] add authorize, capture, void, psync, Webhooks support
  config/Development.toml
  config/config.example.toml
  config/docker_compose.toml
  crates/api_models/src/enums.rs
  crates/router/src/configs/settings.rs
  crates/router/src/connector.rs
  crates/router/src/connector/airwallex.rs
  crates/router/src/connector/airwallex/transformers.rs
  crates/router/src/connector/bluesnap.rs
  crates/router/src/connector/nuvei.rs
  crates/router/src/core/payments/access_token.rs
  crates/router/src/core/payments/transformers.rs
  crates/router/src/core/utils.rs
  crates/router/src/types.rs
  crates/router/src/types/api.rs
  crates/router/tests/connectors/aci.rs
  crates/router/tests/connectors/adyen.rs
  crates/router/tests/connectors/airwallex.rs
  crates/router/tests/connectors/authorizedotnet.rs
  crates/router/tests/connectors/checkout.rs
  crates/router/tests/connectors/connector_auth.rs
  crates/router/tests/connectors/main.rs
  crates/router/tests/connectors/utils.rs
  loadtest/config/Development.toml
Labels: A-connector-integration, C-feature, S-waiting-on-author

#653 feat(router): add foreign_into for attempt status
  crates/api_models/src/enums.rs
  crates/router/src/types/transformers.rs
  crates/storage_models/src/enums.rs
Labels: A-core, C-feature

#654 fix(connector): update Bluesnap in routable connectors
  crates/api_models/src/enums.rs
Labels: A-connector-integration

#615 feat(stripe): get error message for failed redirect payments
  crates/router/src/connector/dlocal/transformers.rs
  crates/router/src/connector/stripe.rs
  crates/router/src/connector/stripe/transformers.rs
  crates/router/src/core/payments/operations/payment_response.rs
Labels: A-connector-compatibility

#656 refactor: Pass country and currency as json format in MCA
  crates/api_models/src/admin.rs
  crates/api_models/src/payment_methods.rs
  crates/router/src/core/admin.rs
  crates/router/src/core/payment_methods/cards.rs
Labels: A-payment-methods, C-refactor

#664 chore: adding build only sandbox feature to reduce build time
  .github/workflows/CI.yml
Labels: A-CI-CD

#660 feat(pm_list): support filter based on disabled connectors
  crates/router/src/core/admin.rs
  crates/router/src/core/payment_methods/cards.rs
  crates/router/src/core/payments/operations/payment_session.rs
  crates/router/src/db/merchant_connector_account.rs
  crates/storage_models/src/query/merchant_connector_account.rs
Labels: C-feature

#662 refactor(pm_list): filter based on shipping country instead of billing country
  crates/router/src/core/payment_methods/cards.rs
Labels: C-refactor

#665 feat(pm_list): support filter based on card_networks and remove unused struct
  crates/api_models/src/payment_methods.rs
  crates/router/src/core/payment_methods/cards.rs
Labels: C-feature

#657 refactor(pm_list): modify pm list to support new api contract
  crates/api_models/src/admin.rs
  crates/api_models/src/enums.rs
  crates/api_models/src/payment_methods.rs
  crates/router/src/core/admin.rs
  crates/router/src/core/payment_methods/cards.rs
  crates/router/src/core/payment_methods/transformers.rs
  crates/router/src/core/payments/operations/payment_session.rs
  crates/router/src/db/merchant_connector_account.rs
  crates/router/src/openapi.rs
  crates/router/src/types/api/admin.rs
  crates/storage_models/src/enums.rs
  crates/storage_models/src/query/merchant_connector_account.rs
Labels: A-core, C-feature

#667 fix(compatibility): map stripe country_code to payment_request country code
  crates/router/src/compatibility/stripe/payment_intents/types.rs
Labels: A-connector-compatibility, C-bug

#666 bugfix: populate empty hashmap and fix card_network filtering logic
  crates/api_models/src/payment_methods.rs
  crates/router/src/core/payment_methods/cards.rs
Labels: C-bug

#670 fix(core): send metadata in payments response
  crates/router/src/core/payments/transformers.rs
Labels: A-core, C-bug

#671 feat(card_network): add additional enum variants
  .typos.toml
  crates/api_models/src/enums.rs
  crates/api_models/src/payments.rs
  crates/router/src/core/refunds/validator.rs
  crates/router/src/types/api/payments.rs
Labels: C-feature

#672 bugfix(refunds): skip validate refunds for card
  crates/router/src/core/refunds/validator.rs
Labels: C-bug

#674 bugfix: populate failed status and add bank_redirect
  crates/api_models/src/enums.rs
  crates/router/src/connector/adyen/transformers.rs
  crates/router/src/core/payments/operations/payment_response.rs
  crates/storage_models/src/enums.rs
Labels: C-bug

#668 chore(workflow): check optional compilation
  .github/workflows/CI.yml
  crates/router/src/core/payment_methods/cards.rs
  crates/storage_models/src/api_keys.rs
Labels: A-CI-CD, S-in-progress

#678 feat(pm_list): support for sending bank names
  config/Development.toml
  crates/api_models/src/payment_methods.rs
  crates/api_models/src/payments.rs
  crates/router/src/configs/settings.rs
  crates/router/src/core/payment_methods/cards.rs
  openapi/generated.json
Labels: C-feature

#658 feat:H1083-L1-L3-L4-L5 [Payment Authorise and Sync] + [Refunds and Sync] + [Redirection Flow (BNPL)] + [3DS Payment and Sync] for MultiSafePay
  Cargo.lock
  config/Development.toml
  config/config.example.toml
  config/docker_compose.toml
  crates/api_models/src/enums.rs
  crates/router/Cargo.toml
  crates/router/src/configs/settings.rs
  crates/router/src/connector.rs
  crates/router/src/connector/adyen/transformers.rs
  crates/router/src/connector/multisafepay.rs
  crates/router/src/connector/multisafepay/transformers.rs
  crates/router/src/connector/utils.rs
  crates/router/src/connector/worldline/transformers.rs
  crates/router/src/types/api.rs
  crates/router/tests/connectors/connector_auth.rs
  crates/router/tests/connectors/main.rs
  crates/router/tests/connectors/multisafepay.rs
  crates/router/tests/connectors/sample_auth.toml
  loadtest/config/Development.toml
Labels: A-connector-integration, C-feature, S-waiting-on-review, M-configuration-changes, juspay-hackathon

#680 feat: Add bank redirect mapping to adyen and stripe
  crates/router/src/connector/adyen.rs
  crates/router/src/connector/adyen/transformers.rs
  crates/router/src/connector/stripe/transformers.rs
Labels: A-connector-integration, S-waiting-on-review

#679 bugfix: check if bank_pm exists and then send
  config/Development.toml
  crates/router/src/core/payment_methods/cards.rs
Labels: C-bug, M-configuration-changes

#681 feat: add support for `ANG` currency
  crates/api_models/src/enums.rs
  crates/storage_models/src/enums.rs
  migrations/2023-02-28-072631_ang-currency/down.sql
  migrations/2023-02-28-072631_ang-currency/up.sql
Labels: A-core, M-database-changes

#685 refactor(pm_list): pm_list for bank redirects
  crates/router/src/core/payment_methods/cards.rs
  crates/router/src/core/payments/helpers.rs
Labels: C-bug

#682 refactor(core): add payment method list route to payment_methods
  crates/router/src/connector/nuvei/transformers.rs
  crates/router/src/routes/app.rs
Labels: A-core, C-refactor

#688 fix(connector): fix wordline tests and visa card issuer support
  crates/router/src/connector/utils.rs
  crates/router/src/connector/worldline/transformers.rs
  crates/router/tests/connectors/worldline.rs
Labels: A-connector-integration, C-bug

#687 feat: store card network for cards
  crates/api_models/src/payment_methods.rs
  crates/router/src/core/payment_methods/cards.rs
  crates/router/src/core/payments/helpers.rs
Labels: C-feature

#690 chore(typos): fix CI typos issue
  .typos.toml
Labels: A-CI-CD

#691 bugfix(adyen): adyen psync fail fix
  crates/router/src/core/payments/operations/payment_status.rs
Labels: C-bug

#683 feat(router): added incoming refund webhooks flow
  crates/api_models/src/enums.rs
  crates/api_models/src/webhooks.rs
  crates/router/src/connector/adyen.rs
  crates/router/src/connector/adyen/transformers.rs
  crates/router/src/core/errors.rs
  crates/router/src/core/webhooks.rs
  crates/router/src/db/refund.rs
  crates/router/src/types/transformers.rs
  crates/storage_models/src/enums.rs
  crates/storage_models/src/query/refund.rs
  migrations/2023-02-28-112730_add_refund_webhook_types/down.sql
  migrations/2023-02-28-112730_add_refund_webhook_types/up.sql
Labels: A-core, C-feature

#693 api contract change for applepay
  crates/api_models/src/payments.rs
  crates/router/src/connector/adyen/transformers.rs
  crates/router/src/connector/nuvei/transformers.rs
  crates/router/src/connector/payu/transformers.rs
  crates/router/src/connector/rapyd/transformers.rs
  crates/router/src/connector/worldpay/transformers.rs
  crates/router/src/core/payments/helpers.rs
  crates/router/src/openapi.rs
  crates/router/tests/connectors/worldpay.rs
Labels: A-connector-integration
